---
# DOEL: Van MicroOS naar een DevOps/Admin Workstation.
# ARCHITECTUUR: Focus op netwerk- en systeem-analyse tools.
- name: "openSUSE MicroOS: Admin & DevOps Toolbox"
  hosts: microos_nodes
  tasks:
    - name: "IDEMPOTENTIE: Installatie Analyse Tools"
      community.general.flatpak:
        name:
          - org.wireshark.Wireshark
          - org.dbvis.DbVisualizer
          - org.filezillaproject.Filezilla
          - com.github.diegoivanme.pika-backup
          - org.remmina.Remmina
        state: present
