# inventory.ini
# Usage: ansible-playbook -i inventory.ini setup-podman-stack.yml
#        ansible-playbook -i inventory.ini deploy-web-stack.yml
#        ansible-playbook -i inventory.ini deploy-rocket-chat.yml

[web_servers]
localhost ansible_connection=local

[web_servers:vars]
ansible_python_interpreter=/usr/bin/python3